# Generated by Django 3.1 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('loc', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=40)),
            ],
        ),
    ]
