# Generated by Django 3.1 on 2020-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='type',
            field=models.CharField(choices=[('Service Based', 'Service Based'), ('Product Based', 'Product Based'), ('Startup', 'Startup')], max_length=30),
        ),
    ]
