# Generated by Django 3.1 on 2020-08-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0002_auto_20200811_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg', models.CharField(max_length=40)),
                ('ctc', models.FloatField()),
                ('exp', models.FloatField()),
                ('loc', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.companymodel')),
            ],
        ),
    ]
